const BASE_PRESET = {
    'master.volume': 0.72,
    'limiter.threshold': -6,
    'oscillator.type': 'sawtooth',
    'oscillator.detune': 0,
    'envelope.attack': 0.015,
    'envelope.decay': 0.22,
    'envelope.sustain': 0.62,
    'envelope.release': 0.45,
    'filter.frequency': 5200,
    'filter.Q': 1.2,
    'filter.type': 'lowpass',
    'reverb.wet': 0.28,
    'reverb.decay': 2.8,
    'reverb.preDelay': 0.06,
    'delay.wet': 0.18,
    'delay.delayTime': 0.32,
    'delay.feedback': 0.28,
    'chorus.wet': 0.32,
    'chorus.frequency': 1.4,
    'chorus.delayTime': 3.5,
    'chorus.depth': 0.4,
    'phaser.wet': 0.2,
    'phaser.frequency': 0.45,
    'phaser.octaves': 3,
    'phaser.baseFrequency': 380,
    'tremolo.wet': 0.15,
    'tremolo.frequency': 8,
    'tremolo.depth': 0.3,
    'vibrato.wet': 0.22,
    'vibrato.frequency': 5.4,
    'vibrato.depth': 0.06,
    'distortion.wet': 0.1,
    'distortion.distortion': 0.25,
    'distortion.oversample': '2x',
    'compressor.threshold': -20,
    'compressor.ratio': 6,
    'compressor.attack': 0.01,
    'compressor.release': 0.18,
    'compressor.knee': 18,
    'bitCrusher.bits': 6,
    'filterLFO.frequency': 0.45,
    'filterLFO.depth': 0.25,
    'filterLFO.min': 260,
    'filterLFO.max': 4200,
    'phaserLFO.frequency': 0.35,
    'phaserLFO.depth': 0.18,
    'phaserLFO.min': 0.2,
    'phaserLFO.max': 6,
    'tremoloLFO.frequency': 3.5,
    'tremoloLFO.depth': 0.22,
    'tremoloLFO.min': 0,
    'tremoloLFO.max': 1,
    'vibratoLFO.frequency': 5.5,
    'vibratoLFO.depth': 0.014,
    'vibratoLFO.min': -0.015,
    'vibratoLFO.max': 0.015,
};

const OPTION_PARAMS = {
    'oscillator.type': ['sine', 'triangle', 'sawtooth', 'square', 'fatsawtooth', 'fatsquare', 'fattriangle'],
    'filter.type': ['lowpass', 'highpass', 'bandpass'],
    'distortion.oversample': ['none', '2x', '4x'],
};

function buildPreset(overrides = {}) {
    return Object.assign({}, BASE_PRESET, overrides);
}

function preset(id, name, overrides, description = '', category = '') {
    return {
        id,
        name,
        description,
        category,
        values: buildPreset(overrides)
    };
}

export const PRESET_CATALOG = [
    preset('warm-horizon-pad', 'Warm Horizon Pad', {
        'oscillator.type': 'fatsawtooth',
        'oscillator.detune': 6,
        'envelope.attack': 0.22,
        'envelope.decay': 0.6,
        'envelope.sustain': 0.85,
        'envelope.release': 1.9,
        'filter.frequency': 3400,
        'filter.Q': 0.9,
        'reverb.wet': 0.54,
        'reverb.decay': 6.2,
        'delay.wet': 0.24,
        'delay.delayTime': 0.46,
        'chorus.wet': 0.52,
        'chorus.depth': 0.65,
        'tremolo.wet': 0.18,
        'tremolo.frequency': 4.2,
        'vibrato.wet': 0.28,
        'vibrato.depth': 0.08,
        'distortion.wet': 0.08,
        'compressor.threshold': -26,
        'compressor.ratio': 8,
        'filterLFO.depth': 0.42,
        'filterLFO.frequency': 0.28,
        'filterLFO.min': 180,
        'filterLFO.max': 5200,
        'vibratoLFO.depth': 0.02,
    }, 'Evolving pad with wide stereo movement.', 'Pad'),
    preset('midnight-keys', 'Midnight Keys', {
        'oscillator.type': 'triangle',
        'oscillator.detune': -2,
        'envelope.attack': 0.01,
        'envelope.decay': 0.18,
        'envelope.sustain': 0.55,
        'envelope.release': 0.38,
        'filter.frequency': 6400,
        'filter.Q': 1.6,
        'reverb.wet': 0.36,
        'reverb.decay': 3.2,
        'delay.wet': 0.32,
        'delay.delayTime': 0.28,
        'chorus.wet': 0.24,
        'chorus.frequency': 0.9,
        'chorus.depth': 0.35,
        'tremolo.wet': 0.12,
        'vibrato.wet': 0.18,
        'distortion.wet': 0.05,
        'compressor.threshold': -18,
        'compressor.ratio': 4.5,
        'bitCrusher.bits': 8,
        'filterLFO.depth': 0.16,
        'filterLFO.frequency': 0.7,
        'phaser.wet': 0.18,
        'phaser.frequency': 0.7,
    }, 'Velvety keys with gentle echoes.', 'Keys'),
    preset('solar-flare-lead', 'Solar Flare Lead', {
        'oscillator.type': 'fatsquare',
        'oscillator.detune': 12,
        'envelope.attack': 0.005,
        'envelope.decay': 0.18,
        'envelope.sustain': 0.32,
        'envelope.release': 0.24,
        'filter.frequency': 7500,
        'filter.Q': 2.8,
        'filter.type': 'bandpass',
        'reverb.wet': 0.2,
        'reverb.decay': 1.4,
        'delay.wet': 0.18,
        'delay.delayTime': 0.18,
        'chorus.wet': 0.18,
        'chorus.frequency': 1.9,
        'chorus.depth': 0.22,
        'tremolo.wet': 0.08,
        'vibrato.wet': 0.34,
        'vibrato.frequency': 7.5,
        'vibrato.depth': 0.12,
        'distortion.wet': 0.46,
        'distortion.distortion': 0.74,
        'distortion.oversample': '4x',
        'compressor.threshold': -14,
        'compressor.ratio': 10,
        'bitCrusher.bits': 10,
        'phaser.wet': 0.26,
        'phaser.frequency': 0.95,
        'filterLFO.depth': 0.3,
        'filterLFO.frequency': 1.4,
    }, 'Cutting lead with focused mid bite.', 'Lead'),
    preset('submerged-bass', 'Submerged Bass', {
        'master.volume': 0.82,
        'oscillator.type': 'square',
        'oscillator.detune': -8,
        'envelope.attack': 0.01,
        'envelope.decay': 0.3,
        'envelope.sustain': 0.9,
        'envelope.release': 0.32,
        'filter.frequency': 180,
        'filter.Q': 1.8,
        'filter.type': 'lowpass',
        'reverb.wet': 0.08,
        'delay.wet': 0.06,
        'chorus.wet': 0.18,
        'phaser.wet': 0.14,
        'tremolo.wet': 0,
        'vibrato.depth': 0.02,
        'distortion.wet': 0.22,
        'distortion.distortion': 0.58,
        'compressor.threshold': -12,
        'compressor.ratio': 12,
        'bitCrusher.bits': 7,
        'filterLFO.min': 80,
        'filterLFO.max': 320,
        'filterLFO.depth': 0.5,
        'filterLFO.frequency': 0.22,
        'tremoloLFO.depth': 0.12,
        'tremoloLFO.frequency': 2.8,
    }, 'Deep rolling bass with subtle motion.', 'Bass'),
    preset('crystal-cascade', 'Crystal Cascade Pluck', {
        'oscillator.type': 'triangle',
        'oscillator.detune': 3,
        'envelope.attack': 0.004,
        'envelope.decay': 0.18,
        'envelope.sustain': 0.2,
        'envelope.release': 0.24,
        'filter.frequency': 6800,
        'filter.Q': 2.1,
        'reverb.wet': 0.42,
        'reverb.decay': 4.4,
        'delay.wet': 0.36,
        'delay.delayTime': 0.38,
        'chorus.wet': 0.28,
        'chorus.depth': 0.48,
        'phaser.wet': 0.24,
        'tremolo.wet': 0.22,
        'tremolo.frequency': 6.8,
        'vibrato.wet': 0.18,
        'vibrato.depth': 0.05,
        'distortion.wet': 0.1,
        'compressor.threshold': -22,
        'compressor.ratio': 5,
        'filterLFO.depth': 0.34,
        'filterLFO.frequency': 1.2,
        'vibratoLFO.depth': 0.018,
    }, 'Bright plucks awash in crystalline echoes.', 'Pluck'),
    preset('velvet-choir', 'Velvet Choir', {
        'oscillator.type': 'sine',
        'oscillator.detune': 14,
        'envelope.attack': 0.35,
        'envelope.decay': 0.9,
        'envelope.sustain': 0.95,
        'envelope.release': 2.8,
        'filter.frequency': 2500,
        'filter.Q': 0.7,
        'filter.type': 'lowpass',
        'reverb.wet': 0.62,
        'reverb.decay': 7.6,
        'delay.wet': 0.22,
        'chorus.wet': 0.58,
        'chorus.frequency': 0.8,
        'chorus.depth': 0.75,
        'phaser.wet': 0.32,
        'phaser.frequency': 0.42,
        'tremolo.wet': 0.32,
        'tremolo.depth': 0.46,
        'tremolo.frequency': 3,
        'vibrato.wet': 0.36,
        'vibrato.depth': 0.11,
        'distortion.wet': 0.05,
        'compressor.threshold': -28,
        'compressor.ratio': 4,
        'filterLFO.depth': 0.48,
        'filterLFO.frequency': 0.22,
        'vibratoLFO.depth': 0.024,
    }, 'Expansive choir with lush modulation.', 'Pad'),
    preset('analog-drift', 'Analog Drift', {
        'oscillator.type': 'fattriangle',
        'oscillator.detune': 9,
        'envelope.attack': 0.06,
        'envelope.decay': 0.5,
        'envelope.sustain': 0.72,
        'envelope.release': 1.1,
        'filter.frequency': 4200,
        'filter.Q': 1.4,
        'reverb.wet': 0.3,
        'delay.wet': 0.26,
        'chorus.wet': 0.4,
        'phaser.wet': 0.32,
        'tremolo.wet': 0.18,
        'vibrato.wet': 0.24,
        'vibrato.depth': 0.09,
        'distortion.wet': 0.18,
        'distortion.distortion': 0.34,
        'compressor.threshold': -19,
        'compressor.ratio': 6,
        'bitCrusher.bits': 9,
        'filterLFO.depth': 0.38,
        'filterLFO.frequency': 0.6,
        'phaserLFO.depth': 0.25,
        'phaserLFO.frequency': 0.4,
    }, 'Vintage poly pad with drifting pitch.', 'Pad'),
    preset('neon-runner', 'Neon Runner', {
        'oscillator.type': 'square',
        'oscillator.detune': 5,
        'envelope.attack': 0.02,
        'envelope.decay': 0.25,
        'envelope.sustain': 0.4,
        'envelope.release': 0.3,
        'filter.frequency': 5400,
        'filter.Q': 1.9,
        'filter.type': 'bandpass',
        'reverb.wet': 0.26,
        'delay.wet': 0.34,
        'delay.delayTime': 0.21,
        'chorus.wet': 0.36,
        'phaser.wet': 0.28,
        'tremolo.wet': 0.3,
        'tremolo.frequency': 7,
        'distortion.wet': 0.32,
        'distortion.distortion': 0.58,
        'compressor.threshold': -16,
        'compressor.ratio': 9,
        'bitCrusher.bits': 6,
        'filterLFO.depth': 0.5,
        'filterLFO.frequency': 1.6,
        'vibrato.wet': 0.3,
        'vibrato.depth': 0.1,
    }, 'Retro lead with rhythmic motion.', 'Lead'),
    preset('lunar-echo', 'Lunar Echo Pad', {
        'oscillator.type': 'fatsquare',
        'oscillator.detune': 7,
        'envelope.attack': 0.28,
        'envelope.decay': 0.72,
        'envelope.sustain': 0.92,
        'envelope.release': 2.1,
        'filter.frequency': 2900,
        'filter.Q': 0.8,
        'reverb.wet': 0.58,
        'reverb.decay': 6.5,
        'reverb.preDelay': 0.12,
        'delay.wet': 0.38,
        'delay.delayTime': 0.52,
        'chorus.wet': 0.44,
        'chorus.depth': 0.68,
        'phaser.wet': 0.36,
        'tremolo.wet': 0.26,
        'tremolo.frequency': 3.4,
        'vibrato.depth': 0.14,
        'filterLFO.depth': 0.62,
        'filterLFO.frequency': 0.18,
        'vibratoLFO.depth': 0.028,
    }, 'Suspended pad drenched in echoes.', 'Pad'),
    preset('dusty-tape', 'Dusty Tape Keys', {
        'oscillator.type': 'triangle',
        'oscillator.detune': -5,
        'envelope.attack': 0.03,
        'envelope.decay': 0.4,
        'envelope.sustain': 0.5,
        'envelope.release': 0.6,
        'filter.frequency': 3600,
        'filter.Q': 1.3,
        'reverb.wet': 0.24,
        'delay.wet': 0.22,
        'chorus.wet': 0.46,
        'chorus.depth': 0.58,
        'phaser.wet': 0.18,
        'tremolo.wet': 0.34,
        'tremolo.frequency': 5.5,
        'vibrato.wet': 0.4,
        'vibrato.frequency': 4.6,
        'vibrato.depth': 0.12,
        'distortion.wet': 0.22,
        'distortion.distortion': 0.38,
        'distortion.oversample': '2x',
        'compressor.threshold': -24,
        'compressor.ratio': 6,
        'bitCrusher.bits': 5,
        'filterLFO.depth': 0.28,
        'filterLFO.frequency': 0.52,
    }, 'Lo-fi keys with wobble and grit.', 'Keys'),
    preset('arctic-glass', 'Arctic Glass', {
        'oscillator.type': 'sine',
        'oscillator.detune': 2,
        'envelope.attack': 0.005,
        'envelope.decay': 0.22,
        'envelope.sustain': 0.25,
        'envelope.release': 0.9,
        'filter.frequency': 6500,
        'filter.Q': 2.4,
        'filter.type': 'highpass',
        'reverb.wet': 0.62,
        'reverb.decay': 5.2,
        'reverb.preDelay': 0.08,
        'delay.wet': 0.28,
        'delay.delayTime': 0.42,
        'chorus.wet': 0.36,
        'phaser.wet': 0.22,
        'tremolo.wet': 0.2,
        'vibrato.depth': 0.09,
        'bitCrusher.bits': 12,
        'filterLFO.depth': 0.32,
        'filterLFO.frequency': 0.95,
        'vibratoLFO.depth': 0.02,
    }, 'Icy bell with shimmering highs.', 'Bell'),
    preset('cosmic-sweep', 'Cosmic Sweep', {
        'oscillator.type': 'fatsawtooth',
        'oscillator.detune': 18,
        'envelope.attack': 0.4,
        'envelope.decay': 0.82,
        'envelope.sustain': 0.88,
        'envelope.release': 2.8,
        'filter.frequency': 2000,
        'filter.Q': 0.7,
        'reverb.wet': 0.64,
        'delay.wet': 0.18,
        'chorus.wet': 0.54,
        'phaser.wet': 0.46,
        'phaser.frequency': 0.3,
        'tremolo.wet': 0.44,
        'tremolo.frequency': 2.6,
        'vibrato.wet': 0.38,
        'distortion.wet': 0.14,
        'distortion.distortion': 0.32,
        'filterLFO.depth': 0.76,
        'filterLFO.frequency': 0.18,
        'filterLFO.min': 120,
        'filterLFO.max': 4400,
        'phaserLFO.depth': 0.42,
        'phaserLFO.frequency': 0.26,
    }, 'Slow sweeping texture with evolving filter.', 'Texture'),
    preset('gritty-sync-bass', 'Gritty Sync Bass', {
        'oscillator.type': 'sawtooth',
        'oscillator.detune': -12,
        'envelope.attack': 0.01,
        'envelope.decay': 0.18,
        'envelope.sustain': 0.7,
        'envelope.release': 0.22,
        'filter.frequency': 250,
        'filter.Q': 2.6,
        'reverb.wet': 0.12,
        'delay.wet': 0.08,
        'chorus.wet': 0.16,
        'phaser.wet': 0.12,
        'tremolo.wet': 0.14,
        'vibrato.wet': 0.08,
        'distortion.wet': 0.58,
        'distortion.distortion': 0.86,
        'distortion.oversample': '4x',
        'compressor.threshold': -10,
        'compressor.ratio': 14,
        'bitCrusher.bits': 4,
        'filterLFO.depth': 0.44,
        'filterLFO.frequency': 0.32,
    }, 'Aggressive bass with heavy saturation.', 'Bass'),
    preset('shimmer-strings', 'Shimmer Verb Strings', {
        'oscillator.type': 'fattriangle',
        'oscillator.detune': 10,
        'envelope.attack': 0.24,
        'envelope.decay': 0.9,
        'envelope.sustain': 0.88,
        'envelope.release': 2.4,
        'filter.frequency': 3100,
        'filter.Q': 1.1,
        'reverb.wet': 0.68,
        'reverb.decay': 7.4,
        'reverb.preDelay': 0.14,
        'delay.wet': 0.26,
        'chorus.wet': 0.48,
        'phaser.wet': 0.3,
        'tremolo.wet': 0.24,
        'vibrato.wet': 0.34,
        'vibrato.depth': 0.1,
        'filterLFO.depth': 0.56,
        'filterLFO.frequency': 0.24,
        'vibratoLFO.depth': 0.026,
    }, 'Glassy string pad with long tail.', 'Pad'),
    preset('phaser-dreamscape', 'Phaser Dreamscape', {
        'oscillator.type': 'fatsawtooth',
        'oscillator.detune': 13,
        'envelope.attack': 0.3,
        'envelope.decay': 0.65,
        'envelope.sustain': 0.82,
        'envelope.release': 2.2,
        'filter.frequency': 2600,
        'filter.Q': 1.2,
        'reverb.wet': 0.52,
        'delay.wet': 0.3,
        'chorus.wet': 0.42,
        'phaser.wet': 0.6,
        'phaser.frequency': 0.24,
        'phaser.octaves': 5,
        'tremolo.wet': 0.4,
        'tremolo.frequency': 2.4,
        'vibrato.wet': 0.26,
        'filterLFO.depth': 0.48,
        'filterLFO.frequency': 0.2,
        'phaserLFO.depth': 0.52,
        'phaserLFO.frequency': 0.18,
    }, 'Wide stereo pad with deep phasing.', 'Texture'),
    preset('pulse-engine', 'Pulse Engine Arp', {
        'oscillator.type': 'square',
        'oscillator.detune': 4,
        'envelope.attack': 0.015,
        'envelope.decay': 0.24,
        'envelope.sustain': 0.42,
        'envelope.release': 0.32,
        'filter.frequency': 4800,
        'filter.Q': 1.9,
        'filter.type': 'bandpass',
        'reverb.wet': 0.38,
        'delay.wet': 0.42,
        'delay.delayTime': 0.25,
        'chorus.wet': 0.34,
        'phaser.wet': 0.24,
        'tremolo.wet': 0.5,
        'tremolo.frequency': 8.5,
        'vibrato.wet': 0.22,
        'distortion.wet': 0.2,
        'compressor.threshold': -18,
        'compressor.ratio': 7,
        'filterLFO.depth': 0.46,
        'filterLFO.frequency': 1.8,
        'tremoloLFO.depth': 0.4,
        'tremoloLFO.frequency': 3.2,
    }, 'Rhythmic pulse ideal for arps.', 'Arp'),
    preset('lofi-vhs', 'Lo-Fi VHS', {
        'oscillator.type': 'triangle',
        'oscillator.detune': -7,
        'envelope.attack': 0.03,
        'envelope.decay': 0.38,
        'envelope.sustain': 0.52,
        'envelope.release': 0.55,
        'filter.frequency': 3200,
        'filter.Q': 1.5,
        'reverb.wet': 0.22,
        'delay.wet': 0.3,
        'delay.delayTime': 0.32,
        'chorus.wet': 0.48,
        'phaser.wet': 0.2,
        'tremolo.wet': 0.42,
        'tremolo.frequency': 5.2,
        'vibrato.wet': 0.52,
        'vibrato.frequency': 4.8,
        'vibrato.depth': 0.16,
        'distortion.wet': 0.16,
        'bitCrusher.bits': 5,
        'filterLFO.depth': 0.32,
        'filterLFO.frequency': 0.48,
    }, 'Wobbly nostalgic keys with tape grit.', 'Keys'),
    preset('deep-sea-organ', 'Deep Sea Organ', {
        'oscillator.type': 'sine',
        'oscillator.detune': 11,
        'envelope.attack': 0.48,
        'envelope.decay': 0.8,
        'envelope.sustain': 0.95,
        'envelope.release': 3.2,
        'filter.frequency': 1800,
        'filter.Q': 0.9,
        'reverb.wet': 0.72,
        'reverb.decay': 8,
        'delay.wet': 0.3,
        'chorus.wet': 0.56,
        'phaser.wet': 0.42,
        'tremolo.wet': 0.5,
        'tremolo.frequency': 2,
        'vibrato.wet': 0.38,
        'distortion.wet': 0.12,
        'filterLFO.depth': 0.62,
        'filterLFO.frequency': 0.16,
        'vibratoLFO.depth': 0.03,
    }, 'Slow evolving organ for ambient beds.', 'Pad'),
    preset('alloy-bells', 'Alloy Bells', {
        'oscillator.type': 'triangle',
        'oscillator.detune': 6,
        'envelope.attack': 0.012,
        'envelope.decay': 0.42,
        'envelope.sustain': 0.28,
        'envelope.release': 1.2,
        'filter.frequency': 5800,
        'filter.Q': 2.6,
        'filter.type': 'highpass',
        'reverb.wet': 0.58,
        'delay.wet': 0.44,
        'delay.delayTime': 0.36,
        'chorus.wet': 0.32,
        'phaser.wet': 0.26,
        'tremolo.wet': 0.36,
        'tremolo.frequency': 6.4,
        'vibrato.wet': 0.24,
        'distortion.wet': 0.14,
        'bitCrusher.bits': 11,
        'filterLFO.depth': 0.28,
        'filterLFO.frequency': 1.1,
    }, 'Metallic bells with sparkling tails.', 'Bell'),
    preset('resonant-drift', 'Resonant Drones', {
        'oscillator.type': 'fatsawtooth',
        'oscillator.detune': 20,
        'envelope.attack': 0.6,
        'envelope.decay': 1.2,
        'envelope.sustain': 1,
        'envelope.release': 4.5,
        'filter.frequency': 1200,
        'filter.Q': 0.6,
        'reverb.wet': 0.76,
        'delay.wet': 0.18,
        'chorus.wet': 0.6,
        'phaser.wet': 0.54,
        'tremolo.wet': 0.46,
        'vibrato.wet': 0.42,
        'distortion.wet': 0.2,
        'filterLFO.depth': 0.8,
        'filterLFO.frequency': 0.14,
        'phaserLFO.depth': 0.48,
        'phaserLFO.frequency': 0.12,
        'vibratoLFO.depth': 0.034,
    }, 'Long drones full of movement.', 'Drone'),
    preset('sparkle-motion', 'Sparkle Motion', {
        'oscillator.type': 'sawtooth',
        'oscillator.detune': 5,
        'envelope.attack': 0.01,
        'envelope.decay': 0.3,
        'envelope.sustain': 0.4,
        'envelope.release': 0.9,
        'filter.frequency': 5200,
        'filter.Q': 2.2,
        'filter.type': 'bandpass',
        'reverb.wet': 0.52,
        'delay.wet': 0.4,
        'chorus.wet': 0.38,
        'phaser.wet': 0.28,
        'tremolo.wet': 0.26,
        'vibrato.wet': 0.3,
        'vibrato.depth': 0.12,
        'filterLFO.depth': 0.44,
        'filterLFO.frequency': 1.4,
        'vibratoLFO.depth': 0.02,
    }, 'Bright shimmer ideal for arpeggios.', 'Arp'),
    preset('digital-rain', 'Digital Rain', {
        'oscillator.type': 'triangle',
        'oscillator.detune': 3,
        'envelope.attack': 0.02,
        'envelope.decay': 0.22,
        'envelope.sustain': 0.28,
        'envelope.release': 0.4,
        'filter.frequency': 6000,
        'filter.Q': 1.8,
        'reverb.wet': 0.42,
        'delay.wet': 0.48,
        'delay.delayTime': 0.22,
        'chorus.wet': 0.3,
        'phaser.wet': 0.18,
        'tremolo.wet': 0.44,
        'tremolo.frequency': 9,
        'vibrato.wet': 0.26,
        'bitCrusher.bits': 8,
        'filterLFO.depth': 0.5,
        'filterLFO.frequency': 2.2,
        'tremoloLFO.depth': 0.36,
        'tremoloLFO.frequency': 4.4,
    }, 'Short blips with cascading repeats.', 'Sequence'),
    preset('vapor-trails', 'Vapor Trails', {
        'oscillator.type': 'fattriangle',
        'oscillator.detune': 9,
        'envelope.attack': 0.25,
        'envelope.decay': 0.72,
        'envelope.sustain': 0.86,
        'envelope.release': 2.6,
        'filter.frequency': 3000,
        'filter.Q': 1.1,
        'reverb.wet': 0.66,
        'delay.wet': 0.3,
        'chorus.wet': 0.5,
        'phaser.wet': 0.34,
        'tremolo.wet': 0.3,
        'vibrato.wet': 0.36,
        'filterLFO.depth': 0.52,
        'filterLFO.frequency': 0.3,
        'vibratoLFO.depth': 0.028,
        'phaserLFO.depth': 0.32,
        'phaserLFO.frequency': 0.24,
    }, 'Lush pad with retro shimmer.', 'Pad'),
    preset('harmonic-bloom', 'Harmonic Bloom', {
        'oscillator.type': 'fatsawtooth',
        'oscillator.detune': 8,
        'envelope.attack': 0.18,
        'envelope.decay': 0.54,
        'envelope.sustain': 0.72,
        'envelope.release': 1.8,
        'filter.frequency': 3600,
        'filter.Q': 1.6,
        'reverb.wet': 0.6,
        'delay.wet': 0.32,
        'chorus.wet': 0.46,
        'phaser.wet': 0.32,
        'tremolo.wet': 0.26,
        'vibrato.wet': 0.3,
        'distortion.wet': 0.16,
        'filterLFO.depth': 0.58,
        'filterLFO.frequency': 0.42,
        'vibratoLFO.depth': 0.024,
    }, 'Blooming chords with harmonic shimmer.', 'Pad'),
    preset('bubble-pop', 'Bubble Pop Synth', {
        'oscillator.type': 'square',
        'oscillator.detune': 2,
        'envelope.attack': 0.008,
        'envelope.decay': 0.18,
        'envelope.sustain': 0.18,
        'envelope.release': 0.32,
        'filter.frequency': 4200,
        'filter.Q': 1.9,
        'filter.type': 'bandpass',
        'reverb.wet': 0.32,
        'delay.wet': 0.38,
        'delay.delayTime': 0.18,
        'chorus.wet': 0.3,
        'phaser.wet': 0.24,
        'tremolo.wet': 0.46,
        'tremolo.frequency': 7.5,
        'vibrato.wet': 0.22,
        'distortion.wet': 0.18,
        'bitCrusher.bits': 9,
        'filterLFO.depth': 0.44,
        'filterLFO.frequency': 1.6,
    }, 'Perky pop-ready synth stabs.', 'Lead'),
    preset('thunder-plucks', 'Thunder Plucks', {
        'oscillator.type': 'sawtooth',
        'oscillator.detune': -4,
        'envelope.attack': 0.006,
        'envelope.decay': 0.24,
        'envelope.sustain': 0.38,
        'envelope.release': 0.42,
        'filter.frequency': 3000,
        'filter.Q': 2.4,
        'reverb.wet': 0.3,
        'delay.wet': 0.24,
        'delay.delayTime': 0.26,
        'chorus.wet': 0.28,
        'phaser.wet': 0.34,
        'tremolo.wet': 0.38,
        'tremolo.frequency': 6.2,
        'vibrato.wet': 0.2,
        'distortion.wet': 0.36,
        'distortion.distortion': 0.6,
        'compressor.threshold': -16,
        'compressor.ratio': 9,
        'filterLFO.depth': 0.4,
        'filterLFO.frequency': 1.2,
    }, 'Punchy plucks with growl.', 'Pluck'),
    preset('vapor-brass', 'Vapor Brass', {
        'oscillator.type': 'fatsquare',
        'oscillator.detune': 6,
        'envelope.attack': 0.12,
        'envelope.decay': 0.5,
        'envelope.sustain': 0.78,
        'envelope.release': 1.1,
        'filter.frequency': 3400,
        'filter.Q': 1.3,
        'reverb.wet': 0.48,
        'delay.wet': 0.32,
        'chorus.wet': 0.44,
        'phaser.wet': 0.36,
        'tremolo.wet': 0.32,
        'vibrato.wet': 0.28,
        'filterLFO.depth': 0.38,
        'filterLFO.frequency': 0.5,
        'vibratoLFO.depth': 0.018,
    }, 'Retro brass pad with vapor flair.', 'Pad'),
    preset('mirage-fm', 'FM Mirage', {
        'oscillator.type': 'triangle',
        'oscillator.detune': 8,
        'envelope.attack': 0.18,
        'envelope.decay': 0.42,
        'envelope.sustain': 0.58,
        'envelope.release': 1.5,
        'filter.frequency': 5200,
        'filter.Q': 1.8,
        'filter.type': 'bandpass',
        'reverb.wet': 0.46,
        'delay.wet': 0.28,
        'chorus.wet': 0.48,
        'phaser.wet': 0.28,
        'tremolo.wet': 0.34,
        'vibrato.wet': 0.42,
        'vibrato.depth': 0.14,
        'distortion.wet': 0.16,
        'bitCrusher.bits': 8,
        'filterLFO.depth': 0.52,
        'filterLFO.frequency': 0.64,
        'vibratoLFO.depth': 0.03,
    }, 'Glassine pad reminiscent of FM tones.', 'Pad'),
    preset('subway-sub', 'Subway Sub Bass', {
        'master.volume': 0.9,
        'oscillator.type': 'sine',
        'oscillator.detune': -3,
        'envelope.attack': 0.01,
        'envelope.decay': 0.24,
        'envelope.sustain': 0.95,
        'envelope.release': 0.4,
        'filter.frequency': 120,
        'filter.Q': 1.4,
        'reverb.wet': 0.06,
        'delay.wet': 0.02,
        'chorus.wet': 0.12,
        'phaser.wet': 0.08,
        'tremolo.wet': 0.1,
        'vibrato.wet': 0.04,
        'distortion.wet': 0.24,
        'distortion.distortion': 0.4,
        'compressor.threshold': -8,
        'compressor.ratio': 16,
        'filterLFO.depth': 0.3,
        'filterLFO.frequency': 0.18,
    }, 'Focused low-end sub bass.', 'Bass'),
    preset('binary-choir', 'Binary Choir', {
        'oscillator.type': 'square',
        'oscillator.detune': 14,
        'envelope.attack': 0.22,
        'envelope.decay': 0.6,
        'envelope.sustain': 0.88,
        'envelope.release': 2.3,
        'filter.frequency': 2800,
        'filter.Q': 1.1,
        'reverb.wet': 0.58,
        'delay.wet': 0.34,
        'chorus.wet': 0.48,
        'phaser.wet': 0.38,
        'tremolo.wet': 0.36,
        'vibrato.wet': 0.48,
        'vibrato.depth': 0.16,
        'distortion.wet': 0.12,
        'filterLFO.depth': 0.54,
        'filterLFO.frequency': 0.26,
        'phaserLFO.depth': 0.38,
        'phaserLFO.frequency': 0.24,
    }, 'Digital choir with choral shimmer.', 'Pad'),
];

const RANDOM_LIMITS = {
    'master.volume': { min: 0.3, max: 1 },
    'limiter.threshold': { min: -24, max: -2 },
    'oscillator.detune': { min: -25, max: 25 },
    'envelope.attack': { min: 0.003, max: 0.8 },
    'envelope.decay': { min: 0.08, max: 1.2 },
    'envelope.sustain': { min: 0.1, max: 1 },
    'envelope.release': { min: 0.1, max: 3.5 },
    'filter.frequency': { min: 120, max: 8000 },
    'filter.Q': { min: 0.5, max: 3 },
    'reverb.wet': { min: 0, max: 0.8 },
    'reverb.decay': { min: 0.8, max: 8 },
    'reverb.preDelay': { min: 0, max: 0.2 },
    'delay.wet': { min: 0, max: 0.6 },
    'delay.delayTime': { min: 0.08, max: 0.6 },
    'delay.feedback': { min: 0.1, max: 0.7 },
    'chorus.wet': { min: 0, max: 0.7 },
    'chorus.frequency': { min: 0.4, max: 2.5 },
    'chorus.delayTime': { min: 1.5, max: 7 },
    'chorus.depth': { min: 0.1, max: 0.9 },
    'phaser.wet': { min: 0, max: 0.7 },
    'phaser.frequency': { min: 0.1, max: 1.2 },
    'phaser.octaves': { min: 1, max: 6 },
    'phaser.baseFrequency': { min: 120, max: 800 },
    'tremolo.wet': { min: 0, max: 0.6 },
    'tremolo.frequency': { min: 1.5, max: 12 },
    'tremolo.depth': { min: 0.05, max: 0.8 },
    'vibrato.wet': { min: 0, max: 0.6 },
    'vibrato.frequency': { min: 3, max: 9 },
    'vibrato.depth': { min: 0.02, max: 0.2 },
    'distortion.wet': { min: 0, max: 0.6 },
    'distortion.distortion': { min: 0.1, max: 0.9 },
    'compressor.threshold': { min: -32, max: -6 },
    'compressor.ratio': { min: 2, max: 16 },
    'compressor.attack': { min: 0.001, max: 0.08 },
    'compressor.release': { min: 0.05, max: 0.6 },
    'compressor.knee': { min: 8, max: 30 },
    'bitCrusher.bits': { min: 3, max: 12 },
    'filterLFO.frequency': { min: 0.1, max: 2.5 },
    'filterLFO.depth': { min: 0, max: 0.8 },
    'filterLFO.min': { min: 80, max: 2000 },
    'filterLFO.max': { min: 1500, max: 18000 },
    'phaserLFO.frequency': { min: 0.1, max: 1 },
    'phaserLFO.depth': { min: 0, max: 0.7 },
    'phaserLFO.min': { min: 0.05, max: 1 },
    'phaserLFO.max': { min: 2, max: 10 },
    'tremoloLFO.frequency': { min: 1, max: 6 },
    'tremoloLFO.depth': { min: 0, max: 0.7 },
    'tremoloLFO.min': { min: 0, max: 0.2 },
    'tremoloLFO.max': { min: 0.5, max: 1 },
    'vibratoLFO.frequency': { min: 3, max: 9 },
    'vibratoLFO.depth': { min: 0, max: 0.05 },
    'vibratoLFO.min': { min: -0.05, max: -0.002 },
    'vibratoLFO.max': { min: 0.002, max: 0.05 },
};

function randomInRange({ min, max }) {
    return min + Math.random() * (max - min);
}

function randomIntInRange({ min, max }) {
    return Math.round(randomInRange({ min, max }));
}

export function generateRandomPreset() {
    const values = buildPreset();

    Object.entries(RANDOM_LIMITS).forEach(([key, range]) => {
        if (key.endsWith('.octaves') || key.endsWith('.bits')) {
            values[key] = randomIntInRange(range);
        } else if (key.endsWith('.frequency') || key.endsWith('.delayTime') || key.endsWith('.attack') || key.endsWith('.decay') || key.endsWith('.release') || key.endsWith('.feedback') || key.endsWith('.depth') || key.endsWith('.min') || key.endsWith('.max') || key.endsWith('.ratio') || key.endsWith('.knee') || key.endsWith('.threshold') || key.endsWith('.preDelay') || key.endsWith('.detune') || key.endsWith('.volume')) {
            values[key] = parseFloat(randomInRange(range).toFixed(3));
        } else {
            values[key] = parseFloat(randomInRange(range).toFixed(3));
        }
    });

    values['oscillator.type'] = OPTION_PARAMS['oscillator.type'][Math.floor(Math.random() * OPTION_PARAMS['oscillator.type'].length)];
    values['filter.type'] = OPTION_PARAMS['filter.type'][Math.floor(Math.random() * OPTION_PARAMS['filter.type'].length)];
    values['distortion.oversample'] = OPTION_PARAMS['distortion.oversample'][Math.floor(Math.random() * OPTION_PARAMS['distortion.oversample'].length)];

    if (values['filterLFO.max'] <= values['filterLFO.min']) {
        values['filterLFO.max'] = values['filterLFO.min'] + 400 + Math.random() * 4000;
    }
    if (values['phaserLFO.max'] <= values['phaserLFO.min']) {
        values['phaserLFO.max'] = values['phaserLFO.min'] + 2 + Math.random() * 6;
    }
    if (values['tremoloLFO.max'] <= values['tremoloLFO.min']) {
        values['tremoloLFO.max'] = values['tremoloLFO.min'] + 0.4 + Math.random() * 0.4;
    }

    const presetName = `Random Patch ${Math.floor(Math.random() * 900 + 100)}`;

    return {
        id: `random-${Date.now()}`,
        name: presetName,
        values,
    };
}

export function getPresetById(id) {
    return PRESET_CATALOG.find(p => p.id === id);
}
