pub mod traits;

// Auto-generated flat module mapping
#[path = "../01_Components/01_Math_Atoms/001_Add/impl.rs"]
pub mod math_atoms_add;
#[path = "../01_Components/01_Math_Atoms/002_Subtract/impl.rs"]
pub mod math_atoms_subtract;
#[path = "../01_Components/01_Math_Atoms/003_Multiply/impl.rs"]
pub mod math_atoms_multiply;
#[path = "../01_Components/01_Math_Atoms/004_Divide/impl.rs"]
pub mod math_atoms_divide;
#[path = "../01_Components/01_Math_Atoms/005_Modulo/impl.rs"]
pub mod math_atoms_modulo;
#[path = "../01_Components/01_Math_Atoms/006_Abs/impl.rs"]
pub mod math_atoms_abs;
#[path = "../01_Components/01_Math_Atoms/007_Negate/impl.rs"]
pub mod math_atoms_negate;
#[path = "../01_Components/01_Math_Atoms/008_Reciprocal/impl.rs"]
pub mod math_atoms_reciprocal;
#[path = "../01_Components/01_Math_Atoms/009_Sign/impl.rs"]
pub mod math_atoms_sign;
#[path = "../01_Components/01_Math_Atoms/010_Ceil/impl.rs"]
pub mod math_atoms_ceil;
#[path = "../01_Components/01_Math_Atoms/011_Floor/impl.rs"]
pub mod math_atoms_floor;
#[path = "../01_Components/01_Math_Atoms/012_Round/impl.rs"]
pub mod math_atoms_round;
#[path = "../01_Components/01_Math_Atoms/013_Frac/impl.rs"]
pub mod math_atoms_frac;
#[path = "../01_Components/01_Math_Atoms/014_Min/impl.rs"]
pub mod math_atoms_min;
#[path = "../01_Components/01_Math_Atoms/015_Max/impl.rs"]
pub mod math_atoms_max;
#[path = "../01_Components/01_Math_Atoms/016_Clamp/impl.rs"]
pub mod math_atoms_clamp;
#[path = "../01_Components/01_Math_Atoms/017_Power/impl.rs"]
pub mod math_atoms_power;
#[path = "../01_Components/01_Math_Atoms/018_Sqrt/impl.rs"]
pub mod math_atoms_sqrt;
#[path = "../01_Components/01_Math_Atoms/019_Log/impl.rs"]
pub mod math_atoms_log;
#[path = "../01_Components/01_Math_Atoms/020_Exp/impl.rs"]
pub mod math_atoms_exp;
#[path = "../01_Components/01_Math_Atoms/021_Sin/impl.rs"]
pub mod math_atoms_sin;
#[path = "../01_Components/01_Math_Atoms/022_Cos/impl.rs"]
pub mod math_atoms_cos;
#[path = "../01_Components/01_Math_Atoms/023_Tan/impl.rs"]
pub mod math_atoms_tan;
#[path = "../01_Components/01_Math_Atoms/024_ArcSin/impl.rs"]
pub mod math_atoms_arcsin;
#[path = "../01_Components/01_Math_Atoms/025_ArcCos/impl.rs"]
pub mod math_atoms_arccos;
#[path = "../01_Components/01_Math_Atoms/026_ArcTan/impl.rs"]
pub mod math_atoms_arctan;
#[path = "../01_Components/01_Math_Atoms/027_ArcTan2/impl.rs"]
pub mod math_atoms_arctan2;
#[path = "../01_Components/01_Math_Atoms/028_Tanh/impl.rs"]
pub mod math_atoms_tanh;
#[path = "../01_Components/02_Logic/029_GreaterThan/impl.rs"]
pub mod logic_greaterthan;
#[path = "../01_Components/02_Logic/030_LessThan/impl.rs"]
pub mod logic_lessthan;
#[path = "../01_Components/02_Logic/031_Equal/impl.rs"]
pub mod logic_equal;
#[path = "../01_Components/02_Logic/032_NotEqual/impl.rs"]
pub mod logic_notequal;
#[path = "../01_Components/02_Logic/033_AND/impl.rs"]
pub mod logic_and;
#[path = "../01_Components/02_Logic/034_OR/impl.rs"]
pub mod logic_or;
#[path = "../01_Components/02_Logic/035_XOR/impl.rs"]
pub mod logic_xor;
#[path = "../01_Components/02_Logic/036_NOT/impl.rs"]
pub mod logic_not;
#[path = "../01_Components/02_Logic/037_NAND/impl.rs"]
pub mod logic_nand;
#[path = "../01_Components/02_Logic/038_Select/impl.rs"]
pub mod logic_select;
#[path = "../01_Components/02_Logic/039_SampleAndHold/impl.rs"]
pub mod logic_sampleandhold;
#[path = "../01_Components/02_Logic/040_Latch/impl.rs"]
pub mod logic_latch;
#[path = "../01_Components/03_Memory/041_BufferAlloc/impl.rs"]
pub mod memory_bufferalloc;
#[path = "../01_Components/03_Memory/042_BufferLength/impl.rs"]
pub mod memory_bufferlength;
#[path = "../01_Components/03_Memory/043_BufferClear/impl.rs"]
pub mod memory_bufferclear;
#[path = "../01_Components/03_Memory/044_BufferRead_Raw/impl.rs"]
pub mod memory_bufferread_raw;
#[path = "../01_Components/03_Memory/045_BufferWrite_Raw/impl.rs"]
pub mod memory_bufferwrite_raw;
#[path = "../01_Components/03_Memory/046_BufferRead_Lin/impl.rs"]
pub mod memory_bufferread_lin;
#[path = "../01_Components/03_Memory/047_BufferRead_Cubic/impl.rs"]
pub mod memory_bufferread_cubic;
#[path = "../01_Components/03_Memory/048_BufferOverdub/impl.rs"]
pub mod memory_bufferoverdub;
#[path = "../01_Components/03_Memory/049_UnitDelay/impl.rs"]
pub mod memory_unitdelay;
#[path = "../01_Components/03_Memory/050_DelayLine/impl.rs"]
pub mod memory_delayline;
#[path = "../01_Components/03_Memory/051_TapDelay/impl.rs"]
pub mod memory_tapdelay;
#[path = "../01_Components/03_Memory/052_AllpassDelay/impl.rs"]
pub mod memory_allpassdelay;
#[path = "../01_Components/03_Memory/053_CombDelay/impl.rs"]
pub mod memory_combdelay;
#[path = "../01_Components/03_Memory/054_RingBuffer/impl.rs"]
pub mod memory_ringbuffer;
#[path = "../01_Components/04_Sources/055_Phasor/impl.rs"]
pub mod sources_phasor;
#[path = "../01_Components/04_Sources/056_SineOsc/impl.rs"]
pub mod sources_sineosc;
#[path = "../01_Components/04_Sources/057_Impulse/impl.rs"]
pub mod sources_impulse;
#[path = "../01_Components/04_Sources/058_WhiteNoise/impl.rs"]
pub mod sources_whitenoise;
#[path = "../01_Components/04_Sources/059_PinkNoise/impl.rs"]
pub mod sources_pinknoise;
#[path = "../01_Components/04_Sources/060_BrownNoise/impl.rs"]
pub mod sources_brownnoise;
#[path = "../01_Components/04_Sources/061_Saw_Naive/impl.rs"]
pub mod sources_saw_naive;
#[path = "../01_Components/04_Sources/062_Pulse_Naive/impl.rs"]
pub mod sources_pulse_naive;
#[path = "../01_Components/04_Sources/063_Tri_Naive/impl.rs"]
pub mod sources_tri_naive;
#[path = "../01_Components/04_Sources/064_Saw_PolyBLEP/impl.rs"]
pub mod sources_saw_polyblep;
#[path = "../01_Components/04_Sources/065_Pulse_PolyBLEP/impl.rs"]
pub mod sources_pulse_polyblep;
#[path = "../01_Components/04_Sources/066_WavetableRead/impl.rs"]
pub mod sources_wavetableread;
#[path = "../01_Components/05_Envelopes/067_Line/impl.rs"]
pub mod envelopes_line;
#[path = "../01_Components/05_Envelopes/068_ExpCurve/impl.rs"]
pub mod envelopes_expcurve;
#[path = "../01_Components/05_Envelopes/069_ADSR/impl.rs"]
pub mod envelopes_adsr;
#[path = "../01_Components/05_Envelopes/070_AR/impl.rs"]
pub mod envelopes_ar;
#[path = "../01_Components/05_Envelopes/071_AHDSR/impl.rs"]
pub mod envelopes_ahdsr;
#[path = "../01_Components/05_Envelopes/072_Follower/impl.rs"]
pub mod envelopes_follower;
#[path = "../01_Components/05_Envelopes/073_FollowerRMS/impl.rs"]
pub mod envelopes_followerrms;
#[path = "../01_Components/05_Envelopes/074_ZeroCrossDetect/impl.rs"]
pub mod envelopes_zerocrossdetect;
#[path = "../01_Components/05_Envelopes/075_SchmidtTrigger/impl.rs"]
pub mod envelopes_schmidttrigger;
#[path = "../01_Components/05_Envelopes/076_LFO/impl.rs"]
pub mod envelopes_lfo;
#[path = "../01_Components/06_Filters/077_OnePoleLP/impl.rs"]
pub mod filters_onepolelp;
#[path = "../01_Components/06_Filters/078_OnePoleHP/impl.rs"]
pub mod filters_onepolehp;
#[path = "../01_Components/06_Filters/079_DCBlocker/impl.rs"]
pub mod filters_dcblocker;
#[path = "../01_Components/06_Filters/080_Biquad/impl.rs"]
pub mod filters_biquad;
#[path = "../01_Components/06_Filters/081_SVF_LP/impl.rs"]
pub mod filters_svf_lp;
#[path = "../01_Components/06_Filters/082_SVF_HP/impl.rs"]
pub mod filters_svf_hp;
#[path = "../01_Components/06_Filters/083_SVF_BP/impl.rs"]
pub mod filters_svf_bp;
#[path = "../01_Components/06_Filters/084_SVF_Notch/impl.rs"]
pub mod filters_svf_notch;
#[path = "../01_Components/06_Filters/085_Ladder_LP/impl.rs"]
pub mod filters_ladder_lp;
#[path = "../01_Components/06_Filters/086_Butterworth/impl.rs"]
pub mod filters_butterworth;
#[path = "../01_Components/06_Filters/087_Shelf/impl.rs"]
pub mod filters_shelf;
#[path = "../01_Components/06_Filters/088_Peaking/impl.rs"]
pub mod filters_peaking;
#[path = "../01_Components/07_Spectral/089_FFT/impl.rs"]
pub mod spectral_fft;
#[path = "../01_Components/07_Spectral/090_iFFT/impl.rs"]
pub mod spectral_ifft;
#[path = "../01_Components/07_Spectral/091_CartToPolar/impl.rs"]
pub mod spectral_carttopolar;
#[path = "../01_Components/07_Spectral/092_PolarToCart/impl.rs"]
pub mod spectral_polartocart;
#[path = "../01_Components/07_Spectral/093_Win_Hann/impl.rs"]
pub mod spectral_win_hann;
#[path = "../01_Components/07_Spectral/094_Win_Hamming/impl.rs"]
pub mod spectral_win_hamming;
#[path = "../01_Components/07_Spectral/095_Win_Blackman/impl.rs"]
pub mod spectral_win_blackman;
#[path = "../01_Components/07_Spectral/096_Convolution/impl.rs"]
pub mod spectral_convolution;
#[path = "../01_Components/08_Timing/097_Metronome/impl.rs"]
pub mod timing_metronome;
#[path = "../01_Components/08_Timing/098_Divider/impl.rs"]
pub mod timing_divider;
#[path = "../01_Components/08_Timing/099_Multiplier/impl.rs"]
pub mod timing_multiplier;
#[path = "../01_Components/08_Timing/100_Counter/impl.rs"]
pub mod timing_counter;
#[path = "../01_Components/08_Timing/101_Accumulator/impl.rs"]
pub mod timing_accumulator;
#[path = "../01_Components/08_Timing/102_Quantizer/impl.rs"]
pub mod timing_quantizer;
#[path = "../01_Components/08_Timing/103_SlewLimiter/impl.rs"]
pub mod timing_slewlimiter;
#[path = "../01_Components/08_Timing/104_Rate/impl.rs"]
pub mod timing_rate;
#[path = "../01_Components/08_Timing/105_HzToMs/impl.rs"]
pub mod timing_hztoms;
#[path = "../01_Components/08_Timing/106_MsToHz/impl.rs"]
pub mod timing_mstohz;
#[path = "../01_Components/08_Timing/107_MidiToHz/impl.rs"]
pub mod timing_miditohz;
#[path = "../01_Components/08_Timing/108_HzToMidi/impl.rs"]
pub mod timing_hztomidi;
#[path = "../01_Components/08_Timing/109_SequencerStep/impl.rs"]
pub mod timing_sequencerstep;
#[path = "../01_Components/08_Timing/110_Euclidean/impl.rs"]
pub mod timing_euclidean;
#[path = "../01_Components/08_Timing/111_Burst/impl.rs"]
pub mod timing_burst;
#[path = "../01_Components/08_Timing/112_Probability/impl.rs"]
pub mod timing_probability;
#[path = "../01_Components/08_Timing/113_Markov/impl.rs"]
pub mod timing_markov;
#[path = "../01_Components/08_Timing/114_DelayTrigger/impl.rs"]
pub mod timing_delaytrigger;
#[path = "../01_Components/08_Timing/115_GateToTrig/impl.rs"]
pub mod timing_gatetotrig;
#[path = "../01_Components/08_Timing/116_Toggle/impl.rs"]
pub mod timing_toggle;
#[path = "../01_Components/09_Effects/117_HardClip/impl.rs"]
pub mod effects_hardclip;
#[path = "../01_Components/09_Effects/118_SoftClip/impl.rs"]
pub mod effects_softclip;
#[path = "../01_Components/09_Effects/119_Bitcrush/impl.rs"]
pub mod effects_bitcrush;
#[path = "../01_Components/09_Effects/120_RateReduce/impl.rs"]
pub mod effects_ratereduce;
#[path = "../01_Components/09_Effects/121_Wavefolder/impl.rs"]
pub mod effects_wavefolder;
#[path = "../01_Components/09_Effects/122_VCA/impl.rs"]
pub mod effects_vca;
#[path = "../01_Components/09_Effects/123_Pan_Lin/impl.rs"]
pub mod effects_pan_lin;
#[path = "../01_Components/09_Effects/124_Pan_Equal/impl.rs"]
pub mod effects_pan_equal;
#[path = "../01_Components/09_Effects/125_MS_Encode/impl.rs"]
pub mod effects_ms_encode;
#[path = "../01_Components/09_Effects/126_MS_Decode/impl.rs"]
pub mod effects_ms_decode;
#[path = "../01_Components/09_Effects/127_Crossfade/impl.rs"]
pub mod effects_crossfade;
#[path = "../01_Components/09_Effects/128_Sidechain/impl.rs"]
pub mod effects_sidechain;
#[path = "../01_Components/10_Utils/129_PeakDetect/impl.rs"]
pub mod utils_peakdetect;
#[path = "../01_Components/10_Utils/130_RMSDetect/impl.rs"]
pub mod utils_rmsdetect;
#[path = "../01_Components/10_Utils/131_ZeroCount/impl.rs"]
pub mod utils_zerocount;
#[path = "../01_Components/10_Utils/132_Spectrum/impl.rs"]
pub mod utils_spectrum;
#[path = "../01_Components/10_Utils/133_Scope/impl.rs"]
pub mod utils_scope;
#[path = "../01_Components/10_Utils/134_PI/impl.rs"]
pub mod utils_pi;
#[path = "../01_Components/10_Utils/135_TAU/impl.rs"]
pub mod utils_tau;
#[path = "../01_Components/10_Utils/136_EULER/impl.rs"]
pub mod utils_euler;
#[path = "../01_Components/10_Utils/137_SampleRate/impl.rs"]
pub mod utils_samplerate;
#[path = "../01_Components/10_Utils/138_Nyquist/impl.rs"]
pub mod utils_nyquist;
#[path = "../01_Components/10_Utils/139_DbToAmp/impl.rs"]
pub mod utils_dbtoamp;
#[path = "../01_Components/10_Utils/140_AmpToDb/impl.rs"]
pub mod utils_amptodb;
#[path = "../01_Components/10_Utils/141_BpmToMs/impl.rs"]
pub mod utils_bpmtoms;
#[path = "../01_Components/10_Utils/142_PhasorToSin/impl.rs"]
pub mod utils_phasortosin;
#[path = "../01_Components/10_Utils/143_PhasorToTri/impl.rs"]
pub mod utils_phasortotri;
#[path = "../01_Components/10_Utils/144_LinToExp/impl.rs"]
pub mod utils_lintoexp;
