// samples.js
export const samples = [
    {
      id: 'kick1',
      name: 'Kick Drum 1',
      url: 'https://ordinals.com/content/83407a1c9637e53e76e3d4de711b971f557e7876ad96b9b520a8202109521ba1i3',
      category: 'drum',
      type: 'kick',
      properties: {
        loop: false,
        trim: false,
        trimStart: 0,
        trimEnd: 0, // Positive value -  will be removed from the end of the sample. EG 0.1 will remove the last 0.1 seconds of the sample.
        volume: 1.0,
        playbackRate: 1.0,
        loopPoints: { bars: 0, beats: 0 },
      },
      note: null,
      userNotes: 'Produces a deep, resonant kick sound suitable for driving beats.',
      description: 'A deep kick drum suitable for hip-hop beats.',
    },
    {
      id: 'snare1',
      name: 'Snare Drum 1',
      url: 'https://ordinals.com/content/83407a1c9637e53e76e3d4de711b971f557e7876ad96b9b520a8202109521ba1i6',
      category: 'drum',
      type: 'snare',
      properties: {
        loop: false,
        trim: false,
        trimStart: 0,
        trimEnd: 0,
        volume: 1.0,
        playbackRate: 1.0,
        loopPoints: { bars: 0, beats: 0 },
      },
      note: null,
      userNotes: 'Provides a sharp attack and crisp snare tone.',
      description: 'A crisp snare with a sharp attack.',
    },
    {
      id: 'hihat1',
      name: 'Hi-Hat 1',
      url: 'https://ordinals.com/content/83407a1c9637e53e76e3d4de711b971f557e7876ad96b9b520a8202109521ba1i0',
      category: 'drum',
      type: 'hihat',
      properties: {
        loop: false,
        trim: true,
        trimStart: 0.05,
        trimEnd: 0.02,
        volume: 0.8,
        playbackRate: 1.0,
        loopPoints: { bars: 0, beats: 0 },
      },
      note: 'F#5',
      userNotes: 'Has a slight delay before the hit, useful for subtle rhythm layering.',
      description: 'A closed hi-hat with a slight delay before the hit.',
    },
    {
        id: 'Dog Bark 1',
        name: 'Dog Bark',
        url: 'https://ordinals.com/content/a48ba6b6e1d3f5a3efde56b07ffabb12ec697d907a9dfd6e8cfa9491f0587ab8i0',
        category: 'tonal',
        type: 'instrument',
        properties: {
          loop: false,
          trim: false,
          trimStart: 0,
          trimEnd: 0,
          volume: 1,
          playbackRate: 1.0,
          loopPoints: { bars: 0, beats: 0 },
        },
        note: 'F#5',
        userNotes: 'Has a slight delay before the hit, useful for subtle rhythm layering.',
        description: 'A closed hi-hat with a slight delay before the hit.',
      },
    
    {
        id: 'rhythmLoop1',
        name: 'Amen Break',
        url: 'https://ordinals.com/content/d52fe368443e3103bfad0f44968e1d9d893c07ca15f608e8e44804afe1484f88i0',
        category: 'loop',
        type: 'rhythm',
        properties: {
          loop: true,
          trim: false,
          trimStart: 0,
          trimEnd: 0.02,
          volume: 1.0,
          playbackRate: 0.33,
          // Removed loopPoints and bpm
        },
        note: null,
        key: 'D Minor',
        tempo: 138,
        userNotes: 'Works well with steady basslines and melodic layers.',
        description: 'A 4-second rhythm loop with seamless looping points.',
      },
    {
      id: 'melodyLoop1',
      name: 'Melody Loop 1',
      url: 'https://ordinals.com/content/5da3c0aab997e63adbbdb4243d215cec6450b5f1e2cc9b918772ea4e35baffefi0',
      category: 'loop',
      type: 'melody',
      properties: {
        loop: true,
        trim: false,
        trimStart: 0,
        trimEnd: 0.035,
        volume: 1.0,
        playbackRate: 1.0,
        loopPoints: { bars: 2, beats: 0 },
        bpm: 80,
      },
      note: null,
      key: 'G Major',
      tempo: 80,
      userNotes: 'Ideal for harmonic progression and background textures.',
      description: 'An 8-second melody loop for harmonic progression.',
    },
    {
      id: 'loop1',
      name: 'Fast Melody Loop',
      url: 'https://example.com/fast_melody_loop.wav',
      category: 'loop',
      type: 'melody',
      properties: {
        loop: true,
        trim: false,
        trimStart: 0,
        trimEnd: 0,
        volume: 1.0,
        playbackRate: 0.33,
        loopPoints: { bars: 1, beats: 0 },
        bpm: 120,
      },
      note: null,
      key: 'C Major',
      tempo: 120,
      userNotes: 'Best for building ambient or melodic textures.',
      description: 'A melody loop uploaded at 300% speed, needs to be slowed down.',
    },
    // Additional samples can follow the same structure
  ];