/**
 * presets.js
 * Love-inspired preset bank for Mothy G
 */

export const DEFAULT_PRESETS = [
  // Romantic Pads
  {
    name: 'Eternal Embrace',
    category: 'Pads',
    params: {
      osc1Type: 'sawtooth',
      osc1Detune: 0,
      osc1Volume: -6,
      filterType: 'lowpass',
      filterFreq: 800,
      filterQ: 1.5,
      filterEnvAmount: 2000,
      ampAttack: 0.8,
      ampDecay: 0.5,
      ampSustain: 0.8,
      ampRelease: 2.0,
      filterAttack: 1.2,
      filterDecay: 0.8,
      filterSustain: 0.6,
      filterRelease: 2.5,
      reverbMix: 0.45,
      reverbDecay: 3.5,
      delayTime: 0.375,
      delayFeedback: 0.25,
      delayMix: 0.15,
      chorusDepth: 0.7,
      chorusRate: 1.5,
      chorusMix: 0.35,
      masterVolume: -8
    }
  },
  {
    name: 'Whispered Dreams',
    category: 'Pads',
    params: {
      osc1Type: 'triangle',
      osc1Detune: 7,
      osc1Volume: -8,
      filterType: 'lowpass',
      filterFreq: 1200,
      filterQ: 0.8,
      filterEnvAmount: 1500,
      ampAttack: 1.5,
      ampDecay: 0.8,
      ampSustain: 0.75,
      ampRelease: 3.0,
      filterAttack: 2.0,
      filterDecay: 1.0,
      filterSustain: 0.5,
      filterRelease: 3.5,
      reverbMix: 0.5,
      reverbDecay: 4.0,
      delayTime: 0.5,
      delayFeedback: 0.3,
      delayMix: 0.2,
      chorusDepth: 0.6,
      chorusRate: 1.2,
      chorusMix: 0.3,
      masterVolume: -10
    }
  },
  {
    name: 'Heartstrings',
    category: 'Pads',
    params: {
      osc1Type: 'sawtooth',
      osc1Detune: -5,
      osc1Volume: -7,
      filterType: 'lowpass',
      filterFreq: 1000,
      filterQ: 2.0,
      filterEnvAmount: 2500,
      ampAttack: 0.6,
      ampDecay: 0.4,
      ampSustain: 0.85,
      ampRelease: 1.8,
      filterAttack: 0.8,
      filterDecay: 0.6,
      filterSustain: 0.7,
      filterRelease: 2.2,
      reverbMix: 0.4,
      reverbDecay: 3.0,
      delayTime: 0.333,
      delayFeedback: 0.35,
      delayMix: 0.18,
      chorusDepth: 0.8,
      chorusRate: 2.0,
      chorusMix: 0.4,
      masterVolume: -7
    }
  },
  
  // Silky Leads
  {
    name: 'Tender Touch',
    category: 'Leads',
    params: {
      osc1Type: 'sawtooth',
      osc1Detune: 0,
      osc1Volume: -3,
      filterType: 'lowpass',
      filterFreq: 2500,
      filterQ: 2.5,
      filterEnvAmount: 4000,
      ampAttack: 0.01,
      ampDecay: 0.3,
      ampSustain: 0.6,
      ampRelease: 0.4,
      filterAttack: 0.02,
      filterDecay: 0.4,
      filterSustain: 0.5,
      filterRelease: 0.6,
      reverbMix: 0.25,
      reverbDecay: 2.0,
      delayTime: 0.25,
      delayFeedback: 0.2,
      delayMix: 0.12,
      chorusDepth: 0.4,
      chorusRate: 3.0,
      chorusMix: 0.2,
      masterVolume: -5
    }
  },
  {
    name: 'Passionate Cry',
    category: 'Leads',
    params: {
      osc1Type: 'square',
      osc1Detune: 0,
      osc1Volume: -4,
      filterType: 'lowpass',
      filterFreq: 3000,
      filterQ: 3.0,
      filterEnvAmount: 5000,
      ampAttack: 0.005,
      ampDecay: 0.2,
      ampSustain: 0.7,
      ampRelease: 0.3,
      filterAttack: 0.01,
      filterDecay: 0.3,
      filterSustain: 0.6,
      filterRelease: 0.5,
      reverbMix: 0.2,
      reverbDecay: 1.8,
      delayTime: 0.375,
      delayFeedback: 0.25,
      delayMix: 0.15,
      chorusDepth: 0.3,
      chorusRate: 2.5,
      chorusMix: 0.15,
      masterVolume: -4
    }
  },
  {
    name: 'Sweet Serenade',
    category: 'Leads',
    params: {
      osc1Type: 'triangle',
      osc1Detune: 3,
      osc1Volume: -5,
      filterType: 'lowpass',
      filterFreq: 2000,
      filterQ: 2.0,
      filterEnvAmount: 3500,
      ampAttack: 0.02,
      ampDecay: 0.25,
      ampSustain: 0.65,
      ampRelease: 0.5,
      filterAttack: 0.03,
      filterDecay: 0.35,
      filterSustain: 0.55,
      filterRelease: 0.7,
      reverbMix: 0.3,
      reverbDecay: 2.5,
      delayTime: 0.5,
      delayFeedback: 0.3,
      delayMix: 0.2,
      chorusDepth: 0.5,
      chorusRate: 2.0,
      chorusMix: 0.25,
      masterVolume: -6
    }
  },
  
  // Gentle Basses
  {
    name: 'Warm Embrace',
    category: 'Bass',
    params: {
      osc1Type: 'sine',
      osc1Detune: 0,
      osc1Volume: 0,
      filterType: 'lowpass',
      filterFreq: 400,
      filterQ: 1.0,
      filterEnvAmount: 800,
      ampAttack: 0.01,
      ampDecay: 0.3,
      ampSustain: 0.8,
      ampRelease: 0.4,
      filterAttack: 0.01,
      filterDecay: 0.4,
      filterSustain: 0.6,
      filterRelease: 0.5,
      reverbMix: 0.1,
      reverbDecay: 1.5,
      delayTime: 0.25,
      delayFeedback: 0.1,
      delayMix: 0.05,
      chorusDepth: 0.3,
      chorusRate: 1.5,
      chorusMix: 0.1,
      masterVolume: -3
    }
  },
  {
    name: 'Gentle Pulse',
    category: 'Bass',
    params: {
      osc1Type: 'triangle',
      osc1Detune: 0,
      osc1Volume: -2,
      filterType: 'lowpass',
      filterFreq: 500,
      filterQ: 1.5,
      filterEnvAmount: 1000,
      ampAttack: 0.005,
      ampDecay: 0.2,
      ampSustain: 0.7,
      ampRelease: 0.3,
      filterAttack: 0.01,
      filterDecay: 0.25,
      filterSustain: 0.5,
      filterRelease: 0.4,
      reverbMix: 0.15,
      reverbDecay: 1.8,
      delayTime: 0.333,
      delayFeedback: 0.15,
      delayMix: 0.08,
      chorusDepth: 0.4,
      chorusRate: 2.0,
      chorusMix: 0.15,
      masterVolume: -4
    }
  },
  
  // Lush Chords
  {
    name: 'Love Letter',
    category: 'Keys',
    params: {
      osc1Type: 'sawtooth',
      osc1Detune: 5,
      osc1Volume: -6,
      filterType: 'lowpass',
      filterFreq: 3500,
      filterQ: 1.2,
      filterEnvAmount: 2000,
      ampAttack: 0.05,
      ampDecay: 0.4,
      ampSustain: 0.6,
      ampRelease: 0.8,
      filterAttack: 0.08,
      filterDecay: 0.5,
      filterSustain: 0.5,
      filterRelease: 1.0,
      reverbMix: 0.35,
      reverbDecay: 2.8,
      delayTime: 0.375,
      delayFeedback: 0.2,
      delayMix: 0.15,
      chorusDepth: 0.6,
      chorusRate: 2.5,
      chorusMix: 0.3,
      masterVolume: -7
    }
  },
  {
    name: 'Moonlit Dance',
    category: 'Keys',
    params: {
      osc1Type: 'triangle',
      osc1Detune: 0,
      osc1Volume: -5,
      filterType: 'lowpass',
      filterFreq: 4000,
      filterQ: 1.0,
      filterEnvAmount: 1500,
      ampAttack: 0.03,
      ampDecay: 0.35,
      ampSustain: 0.65,
      ampRelease: 0.7,
      filterAttack: 0.05,
      filterDecay: 0.4,
      filterSustain: 0.6,
      filterRelease: 0.9,
      reverbMix: 0.3,
      reverbDecay: 2.5,
      delayTime: 0.5,
      delayFeedback: 0.25,
      delayMix: 0.18,
      chorusDepth: 0.5,
      chorusRate: 2.0,
      chorusMix: 0.25,
      masterVolume: -6
    }
  },
  
  // Dreamy Textures
  {
    name: 'Floating Hearts',
    category: 'Textures',
    params: {
      osc1Type: 'sine',
      osc1Detune: 12,
      osc1Volume: -10,
      filterType: 'bandpass',
      filterFreq: 1500,
      filterQ: 3.0,
      filterEnvAmount: 3000,
      ampAttack: 2.0,
      ampDecay: 1.0,
      ampSustain: 0.7,
      ampRelease: 4.0,
      filterAttack: 2.5,
      filterDecay: 1.5,
      filterSustain: 0.5,
      filterRelease: 4.5,
      reverbMix: 0.6,
      reverbDecay: 5.0,
      delayTime: 0.667,
      delayFeedback: 0.4,
      delayMix: 0.3,
      chorusDepth: 0.9,
      chorusRate: 0.8,
      chorusMix: 0.5,
      masterVolume: -12
    }
  },
  {
    name: 'Velvet Sky',
    category: 'Textures',
    params: {
      osc1Type: 'sawtooth',
      osc1Detune: -7,
      osc1Volume: -9,
      filterType: 'highpass',
      filterFreq: 800,
      filterQ: 2.0,
      filterEnvAmount: 1000,
      ampAttack: 1.5,
      ampDecay: 0.8,
      ampSustain: 0.75,
      ampRelease: 3.5,
      filterAttack: 1.8,
      filterDecay: 1.0,
      filterSustain: 0.6,
      filterRelease: 4.0,
      reverbMix: 0.55,
      reverbDecay: 4.5,
      delayTime: 0.5,
      delayFeedback: 0.45,
      delayMix: 0.35,
      chorusDepth: 0.8,
      chorusRate: 1.0,
      chorusMix: 0.45,
      masterVolume: -11
    }
  },
  
  // Bright & Expressive
  {
    name: 'First Kiss',
    category: 'Bright',
    params: {
      osc1Type: 'square',
      osc1Detune: 0,
      osc1Volume: -5,
      filterType: 'lowpass',
      filterFreq: 5000,
      filterQ: 1.5,
      filterEnvAmount: 3000,
      ampAttack: 0.01,
      ampDecay: 0.15,
      ampSustain: 0.5,
      ampRelease: 0.3,
      filterAttack: 0.01,
      filterDecay: 0.2,
      filterSustain: 0.4,
      filterRelease: 0.4,
      reverbMix: 0.25,
      reverbDecay: 2.0,
      delayTime: 0.25,
      delayFeedback: 0.2,
      delayMix: 0.15,
      chorusDepth: 0.4,
      chorusRate: 3.5,
      chorusMix: 0.2,
      masterVolume: -5
    }
  },
  {
    name: 'Butterfly Wings',
    category: 'Bright',
    params: {
      osc1Type: 'triangle',
      osc1Detune: 10,
      osc1Volume: -6,
      filterType: 'lowpass',
      filterFreq: 6000,
      filterQ: 2.0,
      filterEnvAmount: 4000,
      ampAttack: 0.02,
      ampDecay: 0.2,
      ampSustain: 0.55,
      ampRelease: 0.4,
      filterAttack: 0.02,
      filterDecay: 0.25,
      filterSustain: 0.5,
      filterRelease: 0.5,
      reverbMix: 0.3,
      reverbDecay: 2.2,
      delayTime: 0.333,
      delayFeedback: 0.25,
      delayMix: 0.18,
      chorusDepth: 0.6,
      chorusRate: 4.0,
      chorusMix: 0.3,
      masterVolume: -6
    }
  },
  
  // Classic Init
  {
    name: 'Pure Love',
    category: 'Init',
    params: {
      osc1Type: 'sawtooth',
      osc1Detune: 0,
      osc1Volume: 0,
      filterType: 'lowpass',
      filterFreq: 2000,
      filterQ: 1,
      filterEnvAmount: 3000,
      ampAttack: 0.01,
      ampDecay: 0.2,
      ampSustain: 0.7,
      ampRelease: 0.5,
      filterAttack: 0.01,
      filterDecay: 0.3,
      filterSustain: 0.5,
      filterRelease: 0.8,
      reverbMix: 0.2,
      reverbDecay: 2.5,
      delayTime: 0.25,
      delayFeedback: 0.3,
      delayMix: 0.15,
      chorusDepth: 0.5,
      chorusRate: 2,
      chorusMix: 0.2,
      masterVolume: -6
    }
  }
];
